### ISSUE TITLE
Split up file

### ISSUE THREAD

**Issue by tzachshabtay** [ericoporto/agsjs#1]
Hey @ericoporto , really impressive work!

I wanted to try and contribute to this (first to improve the look of the website), but I saw that `ags.js` is 11K lines long, which makes it really hard to understand what's going on.

Can you refactor and split the file to isolate different module files (i.e follow the [single responsibility principle](https://www.toptal.com/software/single-responsibility-principle))? At the very least split up everything that touches the DOM to its own file which will make it easier to play with.

Thanks and keep up the great work.

**Comment by ericoporto** [comment]
@tzachshabtay sorry, I missed your comment! Hope you are well!

I have some write up here : https://github.com/ericoporto/ags/issues/12

And the actual source code is here: https://github.com/ericoporto/ags/tree/emscripten

This is the specific file that needs improvement: https://github.com/ericoporto/ags/blob/emscripten/Emscripten/launcher_index.html

The rest is generated by Emscripten. This repository is just a GitHub Pages so it can be served :)

I wanted to add drag drop file to upload, but couldn't figure out how.

**Comment by ericoporto** [comment]
Oh, and I also disabled GitHub notifications because they were making me crazy, so this may have played a part of me missing your opened issue. I am sorry for that.

**Comment by ericoporto** [comment]
So I unified both html files, the html is the only human editable part currently, it's stored now in the official ags repository under Emscripten. 

Details and readme here: 
https://github.com/adventuregamestudio/ags/tree/master/Emscripten

I can add more comments on the html file or the readme if needed, just ask :)
